import pandas as pd
import numpy as np
from skimage import io as skio


def getDesiredLabelsDF(outputLabelImageFile, outputSeedsTXT):
    """
    From the output label image (<outputLabelImage>) and output seeds (<outputSeedsTXT>) of Farsight,
    creates and returns a pandas data frame with the columns "Seed", "Farsight Output Label" and
    "Desired Replacement Label". The desired label is the line number of the corresponding seed in
    <outputSeedsTXT>
    :param outputLabelImageFile: string, path of the output label image file generated by farsight
    :param outputSeedsTXT: string, path of the output seed text file generated by farsight
    :return: pd.DataFrame
    """

    seeds = np.loadtxt(outputSeedsTXT, dtype=int)

    labelImage = skio.imread(outputLabelImageFile)

    opColumnMap = {"seed": "Seed Location (X, Y, Z)",
                   "currentLabel": "Farsight Output Label",
                   "desiredLabel": "Desired Replacement Label"}

    opDF = pd.DataFrame(columns=[opColumnMap["seed"],
                                 opColumnMap["currentLabel"],
                                 opColumnMap["desiredLabel"]
                                 ]
                        )

    for ind, (z, y, x) in enumerate(seeds):
        print("Doing {}".format((ind, x, y ,z)))
        tempS = pd.Series()
        tempS[opColumnMap["seed"]] = (x, y, z)
        tempS[opColumnMap["currentLabel"]] = labelImage[x, y, z]
        tempS[opColumnMap["desiredLabel"]] = ind

        opDF = opDF.append(tempS, ignore_index=True)

    return opDF



